"use client";

import { Suspense } from "react";
import { useSearchParams } from "next/navigation";

function ReportContent() {
  const params = useSearchParams();
  const ticker = params.get("ticker") || "贵州茅台";
  const code = "600519.SH";

  return (
    <div className="max-w-[720px] mx-auto px-8 py-16">
      <div className="text-center py-12 border-b border-border-light mb-9">
        <div className="font-mono text-[10px] text-ink-tertiary tracking-[0.12em] mb-3.5">DEEP DIVE REPORT</div>
        <h1 className="font-serif text-[28px] font-bold text-ink-primary tracking-[0.04em] leading-tight">{ticker} ({code})</h1>
        <p className="font-serif text-base text-ink-secondary mt-2">护城河坚固，估值具备吸引力</p>
        <p className="font-mono text-[11px] text-ink-tertiary mt-4">2026年5月17日 · 深度研究报告</p>
      </div>

      <div className="grid grid-cols-4 gap-2.5 mb-8">
        {[{l:"财务健康",v:"优秀",c:"text-data-positive"},{l:"估值水平",v:"低估",c:"text-accent"},{l:"成长前景",v:"稳健",c:"text-ink-primary"},{l:"风险等级",v:"中等",c:"text-ink-secondary"}].map(r=>(
          <div key={r.l} className="p-4 text-center bg-bg-surface border border-border-light">
            <div className="text-[10px] text-ink-tertiary font-mono tracking-[0.06em] mb-1">{r.l}</div>
            <div className={`font-serif text-[22px] font-semibold ${r.c}`}>{r.v}</div>
          </div>
        ))}
      </div>

      <div className="grid grid-cols-3 gap-2.5 mb-8">
        {[{l:"当前价格",v:"1,680",s:"CNY"},{l:"加权目标价",v:"1,970",s:"+17.3% 上行空间",sc:"text-accent"},{l:"综合评级",v:"买入",s:"置信度 72%",sc:"text-accent"}].map(k=>(
          <div key={k.l} className="p-5 text-center bg-bg-surface border border-border-light">
            <div className="text-[10px] text-ink-tertiary font-mono tracking-[0.06em] mb-1">{k.l}</div>
            <div className="font-display text-[34px] font-bold text-ink-primary leading-tight">{k.v}</div>
            <div className={`text-[11px] mt-0.5 ${k.sc||"text-ink-tertiary"}`}>{k.s}</div>
          </div>
        ))}
      </div>

      <div className="border-t border-b border-border-light py-5 mb-8">
        <div className="font-serif text-[15px] font-semibold text-ink-primary mb-3.5">目录</div>
        <div className="grid grid-cols-2 gap-y-1 gap-x-6">
          {["1. 投资摘要","2. 公司概况","3. 行业分析","4. 财务分析","5. 估值分析","6. 风险提示","7. 投资建议"].map(s=>(
            <div key={s} className="text-[13px] text-ink-secondary py-1 cursor-pointer hover:text-accent transition-colors">{s}</div>
          ))}
        </div>
      </div>

      <div className="p-8 bg-bg-surface border border-dashed border-border text-center mb-8">
        <div className="flex items-end justify-center gap-2.5 h-[100px]">
          {[40,55,45,70,55,82,62,75].map((h,i)=>(
            <div key={i} className={`flex-1 max-w-[40px] ${h===82?"bg-accent":"bg-data-series-3"} opacity-70`} style={{height:`${h}%`}}/>
          ))}
        </div>
        <div className="text-[11px] text-ink-tertiary mt-3.5">营收/净利润趋势（2019–2025）· 单位：亿元</div>
      </div>

      <div className="mb-8">
        <div className="font-serif text-[17px] font-semibold text-ink-primary mb-3.5">估值分析</div>
        <div className="grid grid-cols-2 gap-1">
          {[{l:"DCF 三阶段",v:"1,950.00"},{l:"Owner Earnings",v:"2,100.00"},{l:"EV / EBITDA",v:"1,850.00"},{l:"加权目标价",v:"1,970.25",h:true}].map(r=>(
            <div key={r.l} className={`p-2.5 px-3.5 flex justify-between text-[13px] ${r.h?"bg-accent-soft font-semibold":"bg-bg-surface"}`}>
              <span className="text-ink-tertiary">{r.l}</span>
              <span className={`font-mono ${r.h?"text-accent font-semibold":"text-ink-primary"}`}>{r.v}</span>
            </div>
          ))}
        </div>
      </div>

      <div className="mb-8">
        <div className="font-serif text-[17px] font-semibold text-ink-primary mb-3.5">风险提示</div>
        <div className="text-[13px] text-ink-secondary leading-relaxed">
          <p>核心风险：消费降级下高端白酒需求放缓；行业监管趋严；宏观经济放缓抑制商务消费场景。</p>
          <p className="mt-2">核心机遇：直销占比提升推升净利率；品牌壁垒为行业最强；DCF 模型显示 17.3% 上行空间。</p>
        </div>
      </div>

      <div className="flex justify-center gap-4 mb-12">
        <button className="px-6 py-2.5 text-[13px] font-sans border border-border bg-bg-surface text-ink-primary cursor-pointer hover:bg-bg-warm transition-colors">导出 PDF</button>
        <button className="px-6 py-2.5 text-[13px] font-sans border border-border bg-bg-surface text-ink-primary cursor-pointer hover:bg-bg-warm transition-colors">导出 Word</button>
      </div>

      <div className="text-center pt-12 border-t border-border-light text-[11px] text-ink-tertiary">
        AI 辅助生成 · 仅供参考 · 不构成投资建议<br/>Generated by 研报 Agent · Research Platform
      </div>
    </div>
  );
}

export default function ReportPage() {
  return (
    <Suspense fallback={<div className="max-w-[720px] mx-auto px-8 py-12 text-center text-ink-tertiary">加载报告…</div>}>
      <ReportContent />
    </Suspense>
  );
}
